<a href="https://colab.research.google.com/github/Nokibulofficial18/web-dev-ph/blob/main/svd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Theory
X = UDV_transpose;
U=X * X_transpose
V = X_transpose * X
D=eigen(U) * eigen(V) in diagonal and rest are zero.

In [ ]:
X = np.array([[3, 3, 2], [2, 3, -2]])
print(X)


[[ 3  3  2]
 [ 2  3 -2]]


In [ ]:
transpose_X = X.T
print(transpose_X)

[[ 3  2]
 [ 3  3]
 [ 2 -2]]


Finding out U and V

In [ ]:
XXt = np.dot(X,transpose_X)
XtX = np.dot(transpose_X,X)
print(XXt)
print(XtX)

[[22 11]
 [11 17]]
[[13 15  2]
 [15 18  0]
 [ 2  0  8]]


Calculate eigenvalues and eigenvectors of X^T * X (for V) and X * X^T (for U)

In [ ]:
eigvals_XtX, V = np.linalg.eig(XtX)
eigvals_XXt, U = np.linalg.eig(XXt)


Singular values are square roots of eigenvalues (sorted)

In [ ]:
singular_vals = np.sqrt(np.abs(eigvals_XtX))
print(singular_vals)

[5.54801894e+00 5.28151053e-08 2.86696457e+00]


Sorting singular values and associated vectors

In [ ]:
sorted_idx = np.argsort(-singular_vals)
singular_vals = singular_vals[sorted_idx]
print(sorted_idx)

[0 2 1]


Construct Sigma (singular value matrix) in diagonal form

In [ ]:
print(X.shape)
Sigma = np.zeros((X.shape[0], X.shape[1]))
np.fill_diagonal(Sigma,singular_vals)


(2, 3)


In [ ]:
print("U:\n", U)
print("Singular values (diagonal matrix):\n", Sigma)
print("V^T:\n", V.T)

U:
 [[ 0.7815437 -0.6238505]
 [ 0.6238505  0.7815437]]
Singular values (diagonal matrix):
 [[5.54801894 0.         0.        ]
 [0.         2.86696457 0.        ]]
V^T:
 [[ 0.64749817  0.7599438   0.05684667]
 [ 0.75443354 -0.62869461 -0.18860838]
 [ 0.10759258 -0.16501062  0.9804057 ]]
